version: '3.8'

services:
  bot:
    build: .
    command: python app/bot/main.py
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      PYTHONPATH: /code
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONPATH: /code
  alembic:
    image: web
    volumes:
      - .:/code
    entrypoint: ["alembic", "upgrade", "head"]
    env_file:
      - .env
