"""Add exchange_rate to Currency

Revision ID: 0de35ee7a5ef
Revises: 38602499e235
Create Date: 2024-06-12 15:01:17.877600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de35ee7a5ef'
down_revision: Union[str, None] = '38602499e235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('exchange_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'exchange_rate')
    # ### end Alembic commands ###
