"""Autoincrement Wallet ID, transaction

Revision ID: 5c0e1cd85a7c
Revises: 98cbf1dd7a8a
Create Date: 2024-06-12 18:34:21.582790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0e1cd85a7c'
down_revision: Union[str, None] = '98cbf1dd7a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
