"""Autoincrement Currency ID

Revision ID: 98cbf1dd7a8a
Revises: 0de35ee7a5ef
Create Date: 2024-06-12 15:11:08.582938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cbf1dd7a8a'
down_revision: Union[str, None] = '0de35ee7a5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
