"""Set up cascading deletes

Revision ID: e76455871251
Revises: 5c0e1cd85a7c
Create Date: 2024-06-12 18:41:37.072225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76455871251'
down_revision: Union[str, None] = '5c0e1cd85a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_wallet_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallets', ['wallet_id'], ['wallet_id'], ondelete='CASCADE')
    op.drop_constraint('wallets_currency_id_fkey', 'wallets', type_='foreignkey')
    op.drop_constraint('wallets_user_id_fkey', 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wallets', 'currencies', ['currency_id'], ['currency_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key('wallets_user_id_fkey', 'wallets', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('wallets_currency_id_fkey', 'wallets', 'currencies', ['currency_id'], ['currency_id'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_wallet_id_fkey', 'transactions', 'wallets', ['wallet_id'], ['wallet_id'])
    # ### end Alembic commands ###
